:PROPERTIES:
:ID:       b0809c63-59b2-4ae2-af06-e028a1964a6b
:END:
* About

Plot a spectrum from a CSV file using the format of =rtl_power= from [[https://gitea.osmocom.org/sdr/rtl-sdr.git][RTL-SDR]].

* Motivation

This is a fork of [[https://github.com/keenerd/rtl-sdr-misc/blob/master/heatmap/heatmap.py][Kyle "Keenerd" Keen]] repository, only keeping files under the
original =heatmap= directory. His version is unmaintained since several years,
yet this utility is still useful for spectrum offline plotting. In this fork, I
only maintain compatibility with newer versions of Python and dependent
libraries.

* Installation

In the current directory, simply =wget= the needed utility and launch it with
=python=. For example:

#+begin_src bash :eval never
wget https://raw.githubusercontent.com/pierreay/heatmap/master/heatmap.py
python heatmap.py
#+end_src

* Utilities

- [[file:flatten.py][flatten.py]] :: Summarize a =rtl_power= CSV by printing to the standard
  output the magnitude of each frequency band over the whole sweeping time.
- [[file:heatmap.py][heatmap.py]] :: Plot a =rtl_power= CSV into an image representing the
  spectrum.
- [[file:raw_iq.py][raw_iq.py]] :: Plot raw I/Q data (/e.g./, =numpy.complex64=) into the same
  image format and style that =heatmap.py=.
